name: CI Display Name

on: # тригер
  push:
    branches: [way_a]
jobs:
  build_and_tests_display_name:
    runs-on: ubuntu-latest

    steps:
      - name: build code
        uses: ./gradlew assemble
      - name: test func
        uses: ./gradlew test --rerun-tasks
