name: CI Display Name

on: # тригер
  push:
    branches: [way_a]
jobs: # задачи
  build_and_tests_display_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Give permissions for gradlew
        run: chmod +x gradlew

      - name: Build code
        run: ./gradlew assemble

      - name: Test func
        run: ./gradlew test --rerun-tasks
