name: CI Display Name

on: # тригер
  push:
    branches: [way_a]
jobs: # задачи
  build_and_tests_display_name:
    runs-on: ubuntu-latest

    steps:
      - name: build code
        run: ./gradlew assemble
      - name: test func
        run: ./gradlew test --rerun-tasks
